#pragma once

//
// This file contains all IDs of game assets 
//

#define ID_TEX_MARIO 0
#define ID_TEX_ENEMY 10
#define ID_TEX_MISC 20
#define ID_TEX_ENEMY2 30


#define OBJECT_TYPE_MARIO	0
#define OBJECT_TYPE_BRICK	1
#define OBJECT_TYPE_GOOMBA	2
#define OBJECT_TYPE_KOOPAS	3
#define OBJECT_TYPE_COIN 4
#define OBJECT_TYPE_PLATFORM 5
#define OBJECT_TYPE_BACKGROUND	6
#define OBJECT_TYPE_COLORBOX	7
#define OBJECT_TYPE_CHIMNEY	8
#define OBJECT_TYPE_GIFTBOX	9
#define OBJECT_TYPE_WINGED_GOOMBA 10


#define OBJECT_TYPE_PORTAL	50


#pragma region MARIO 

#define ID_SPRITE_MARIO 10000
#define ID_SPRITE_MARIO_BIG (ID_SPRITE_MARIO + 1000)
#define ID_SPRITE_MARIO_BIG_IDLE (ID_SPRITE_MARIO_BIG + 100)
#define ID_SPRITE_MARIO_BIG_IDLE_LEFT (ID_SPRITE_MARIO_BIG_IDLE + 10)
#define ID_SPRITE_MARIO_BIG_IDLE_RIGHT (ID_SPRITE_MARIO_BIG_IDLE + 20)

#define ID_SPRITE_MARIO_BIG_WALKING (ID_SPRITE_MARIO_BIG + 200)
#define ID_SPRITE_MARIO_BIG_WALKING_LEFT (ID_SPRITE_MARIO_BIG_WALKING + 10)
#define ID_SPRITE_MARIO_BIG_WALKING_RIGHT (ID_SPRITE_MARIO_BIG_WALKING + 20)
#define ID_SPRITE_MARIO_BIG_RUNNING (ID_SPRITE_MARIO_BIG + 300)
#define ID_SPRITE_MARIO_BIG_RUNNING_LEFT (ID_SPRITE_MARIO_BIG_RUNNING + 10)
#define ID_SPRITE_MARIO_BIG_RUNNING_RIGHT (ID_SPRITE_MARIO_BIG_RUNNING + 20)
#define ID_SPRITE_MARIO_BIG_JUMP (ID_SPRITE_MARIO_BIG + 400)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK (ID_SPRITE_MARIO_BIG_JUMP + 10)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_LEFT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN (ID_SPRITE_MARIO_BIG_JUMP + 20)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_LEFT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 6)
#define ID_SPRITE_MARIO_BIG_SIT (ID_SPRITE_MARIO_BIG + 500)
#define ID_SPRITE_MARIO_BIG_SIT_LEFT (ID_SPRITE_MARIO_BIG_SIT + 10)
#define ID_SPRITE_MARIO_BIG_SIT_RIGHT (ID_SPRITE_MARIO_BIG_SIT + 20)
#define ID_SPRITE_MARIO_BIG_BRACE (ID_SPRITE_MARIO_BIG + 600)
#define ID_SPRITE_MARIO_BIG_BRACE_LEFT (ID_SPRITE_MARIO_BIG_BRACE + 10)
#define ID_SPRITE_MARIO_BIG_BRACE_RIGHT (ID_SPRITE_MARIO_BIG_BRACE + 20)
#define ID_SPRITE_MARIO_BIG_HOLD (ID_SPRITE_MARIO_BIG + 700)
#define ID_SPRITE_MARIO_BIG_HOLD_LEFT (ID_SPRITE_MARIO_BIG_HOLD + 10)
#define ID_SPRITE_MARIO_BIG_HOLD_RIGHT (ID_SPRITE_MARIO_BIG_HOLD + 20)

#define ID_SPRITE_MARIO_DIE (ID_SPRITE_MARIO + 4000)

#define ID_SPRITE_MARIO_SMALL (ID_SPRITE_MARIO + 2000)
#define ID_SPRITE_MARIO_SMALL_IDLE (ID_SPRITE_MARIO_SMALL + 100)
#define ID_SPRITE_MARIO_SMALL_IDLE_LEFT (ID_SPRITE_MARIO_SMALL_IDLE + 10)
#define ID_SPRITE_MARIO_SMALL_IDLE_RIGHT (ID_SPRITE_MARIO_SMALL_IDLE + 20)

#define ID_SPRITE_MARIO_SMALL_WALKING (ID_SPRITE_MARIO_SMALL + 200)
#define ID_SPRITE_MARIO_SMALL_WALKING_LEFT (ID_SPRITE_MARIO_SMALL_WALKING + 10)
#define ID_SPRITE_MARIO_SMALL_WALKING_RIGHT (ID_SPRITE_MARIO_SMALL_WALKING + 20)
#define ID_SPRITE_MARIO_SMALL_RUNNING (ID_SPRITE_MARIO_SMALL + 300)
#define ID_SPRITE_MARIO_SMALL_RUNNING_LEFT (ID_SPRITE_MARIO_SMALL_RUNNING + 10)
#define ID_SPRITE_MARIO_SMALL_RUNNING_RIGHT (ID_SPRITE_MARIO_SMALL_RUNNING + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP (ID_SPRITE_MARIO_SMALL + 400)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK (ID_SPRITE_MARIO_SMALL_JUMP + 10)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN (ID_SPRITE_MARIO_SMALL_JUMP + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 6)

#define ID_SPRITE_MARIO_SMALL_SIT (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_SIT_LEFT (ID_SPRITE_MARIO_SMALL_SIT + 10)
#define ID_SPRITE_MARIO_SMALL_SIT_RIGHT (ID_SPRITE_MARIO_SMALL_SIT + 20)

#define ID_SPRITE_MARIO_SMALL_BRACE (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_BRACE_LEFT (ID_SPRITE_MARIO_SMALL_BRACE + 10)
#define ID_SPRITE_MARIO_SMALL_BRACE_RIGHT (ID_SPRITE_MARIO_SMALL_BRACE + 20)
#define ID_SPRITE_MARIO_SMALL_HOLD (ID_SPRITE_MARIO_SMALL + 700)
#define ID_SPRITE_MARIO_SMALL_HOLD_LEFT (ID_SPRITE_MARIO_SMALL_HOLD + 10)
#define ID_SPRITE_MARIO_SMALL_HOLD_RIGHT (ID_SPRITE_MARIO_SMALL_HOLD + 20)

#define ID_SPRITE_MARIO_MAX (ID_SPRITE_MARIO + 3000)
#define ID_SPRITE_MARIO_MAX_IDLE (ID_SPRITE_MARIO_MAX + 100)
#define ID_SPRITE_MARIO_MAX_IDLE_LEFT (ID_SPRITE_MARIO_MAX_IDLE + 10)
#define ID_SPRITE_MARIO_MAX_IDLE_RIGHT (ID_SPRITE_MARIO_MAX_IDLE + 20)

#define ID_SPRITE_MARIO_MAX_WALKING (ID_SPRITE_MARIO_MAX + 200)
#define ID_SPRITE_MARIO_MAX_WALKING_LEFT (ID_SPRITE_MARIO_MAX_WALKING + 10)
#define ID_SPRITE_MARIO_MAX_WALKING_RIGHT (ID_SPRITE_MARIO_MAX_WALKING + 20)
#define ID_SPRITE_MARIO_MAX_RUNNING (ID_SPRITE_MARIO_MAX + 300)
#define ID_SPRITE_MARIO_MAX_RUNNING_LEFT (ID_SPRITE_MARIO_MAX_RUNNING + 10)
#define ID_SPRITE_MARIO_MAX_RUNNING_RIGHT (ID_SPRITE_MARIO_MAX_RUNNING + 20)
#define ID_SPRITE_MARIO_MAX_JUMP (ID_SPRITE_MARIO_MAX + 400)
#define ID_SPRITE_MARIO_MAX_JUMP_WALK (ID_SPRITE_MARIO_MAX_JUMP + 10)
#define ID_SPRITE_MARIO_MAX_JUMP_WALK_LEFT (ID_SPRITE_MARIO_MAX_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_MAX_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_MAX_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_MAX_JUMP_RUN (ID_SPRITE_MARIO_MAX_JUMP + 20)
#define ID_SPRITE_MARIO_MAX_JUMP_RUN_LEFT (ID_SPRITE_MARIO_MAX_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_MAX_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_MAX_JUMP_RUN + 6)

#define ID_SPRITE_MARIO_MAX_SIT (ID_SPRITE_MARIO_MAX + 500)
#define ID_SPRITE_MARIO_MAX_SIT_LEFT (ID_SPRITE_MARIO_MAX_SIT + 10)
#define ID_SPRITE_MARIO_MAX_SIT_RIGHT (ID_SPRITE_MARIO_MAX_SIT + 20)

#define ID_SPRITE_MARIO_MAX_BRACE (ID_SPRITE_MARIO_MAX + 500)
#define ID_SPRITE_MARIO_MAX_BRACE_LEFT (ID_SPRITE_MARIO_MAX_BRACE + 10)
#define ID_SPRITE_MARIO_MAX_BRACE_RIGHT (ID_SPRITE_MARIO_MAX_BRACE + 20)
#define ID_SPRITE_MARIO_MAX_HOLD (ID_SPRITE_MARIO_MAX + 700)
#define ID_SPRITE_MARIO_MAX_HOLD_LEFT (ID_SPRITE_MARIO_MAX_HOLD + 10)
#define ID_SPRITE_MARIO_MAX_HOLD_RIGHT (ID_SPRITE_MARIO_MAX_HOLD + 20)


#pragma endregion 

#define ID_SPRITE_BRICK 20000

#define ID_SPRITE_GOOMBA 30000
#define ID_SPRITE_GOOMBA_WALK (ID_SPRITE_GOOMBA + 1000)
#define ID_SPRITE_GOOMBA_DIE (ID_SPRITE_GOOMBA + 2000)

#define ID_SPRITE_COIN 40000

#define ID_SPRITE_CLOUD 50000
#define ID_SPRITE_CLOUD_BEGIN (ID_SPRITE_CLOUD+1000)
#define ID_SPRITE_CLOUD_MIDDLE (ID_SPRITE_CLOUD+2000)
#define ID_SPRITE_CLOUD_END (ID_SPRITE_CLOUD+3000)

#define ID_ANI_KOOPAS_WALKING 6000
#define ID_ANI_KOOPAS_SHELL 6001
#define ID_ANI_KOOPAS_SHELL_MOVING 6002

#define ID_ANI_WINGED_GOOMBA_WALKING 8000
#define ID_ANI_WINGED_GOOMBA_DIE 8001
#define ID_ANI_WINGED_GOOMBA_FLYING 8002
#define ID_ANI_WINGED_GOOMBA_FLYING_LEFT 8003
