#pragma once

//
// This file contains all IDs of game assets 
//

#define ID_TEX_MARIO 0
#define ID_TEX_ENEMY 10
#define ID_TEX_MISC 20
#define ID_TEX_ENEMY2 30


#define OBJECT_TYPE_MARIO	0
#define OBJECT_TYPE_BRICK	1
#define OBJECT_TYPE_GOOMBA	2
#define OBJECT_TYPE_KOOPAS	3
#define OBJECT_TYPE_COIN 4
#define OBJECT_TYPE_PLATFORM 5
#define OBJECT_TYPE_BACKGROUND	6
#define OBJECT_TYPE_COLORBOX	7
#define OBJECT_TYPE_CHIMNEY	8
#define OBJECT_TYPE_GIFTBOX	9
#define OBJECT_TYPE_WINGED_GOOMBA 10
#define OBJECT_TYPE_MUSHROOM	11
#define OBJECT_TYPE_FLOWER	13
#define OBJECT_TYPE_BULLET	15
#define OBJECT_TYPE_LEAF	17
#define OBJECT_TYPE_DARK_BACKGROUND	19
#define OBJECT_TYPE_TRANSCRIPT	21
#define OBJECT_TYPE_NUMBER	23
#define OBJECT_TYPE_GRASSPLATFORM	25
#define OBJECT_TYPE_MOVABLEPLATFORM	27
#define OBJECT_TYPE_BOMERANGBRO	29
#define OBJECT_TYPE_BOMERANG	31
#define OBJECT_TYPE_COIN_BRICK	33
#define WINGED_RED_KOOPA	35
#define BLACK_GIFT_BOX	37


#define OBJECT_TYPE_PIRANHA_PLANT 12
#define OBJECT_TYPE_BREAKABLE_BRICK 14
#define OBJECT_TYPE_BREAKABLE_BRICK 14
#define OBJECT_TYPE_HIDDEN_BUTTON 16
#define OBJECT_TYPE_WINGED_KOOPAS 18
#define OBJECT_TYPE_BREAKABLE_BRICK_CHAIN 20
 

#define OBJECT_TYPE_PORTAL	50

// Effect 
#define OBJECT_TYPE_EFFECTCOINBOX 60
#define OBJECT_TYPE_EFFECTPOINT 61
#define OBJECT_TYPE_EFFECTBULLET 62


#pragma region MARIO 

#define ID_SPRITE_MARIO 10000
#define ID_SPRITE_MARIO_BIG (ID_SPRITE_MARIO + 1000)
#define ID_SPRITE_MARIO_BIG_IDLE (ID_SPRITE_MARIO_BIG + 100)
#define ID_SPRITE_MARIO_BIG_IDLE_LEFT (ID_SPRITE_MARIO_BIG_IDLE + 10)
#define ID_SPRITE_MARIO_BIG_IDLE_RIGHT (ID_SPRITE_MARIO_BIG_IDLE + 20)

#define ID_SPRITE_MARIO_BIG_WALKING (ID_SPRITE_MARIO_BIG + 200)
#define ID_SPRITE_MARIO_BIG_WALKING_LEFT (ID_SPRITE_MARIO_BIG_WALKING + 10)
#define ID_SPRITE_MARIO_BIG_WALKING_RIGHT (ID_SPRITE_MARIO_BIG_WALKING + 20)
#define ID_SPRITE_MARIO_BIG_RUNNING (ID_SPRITE_MARIO_BIG + 300)
#define ID_SPRITE_MARIO_BIG_RUNNING_LEFT (ID_SPRITE_MARIO_BIG_RUNNING + 10)
#define ID_SPRITE_MARIO_BIG_RUNNING_RIGHT (ID_SPRITE_MARIO_BIG_RUNNING + 20)
#define ID_SPRITE_MARIO_BIG_JUMP (ID_SPRITE_MARIO_BIG + 400)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK (ID_SPRITE_MARIO_BIG_JUMP + 10)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_LEFT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN (ID_SPRITE_MARIO_BIG_JUMP + 20)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_LEFT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 6)
#define ID_SPRITE_MARIO_BIG_SIT (ID_SPRITE_MARIO_BIG + 500)
#define ID_SPRITE_MARIO_BIG_SIT_LEFT (ID_SPRITE_MARIO_BIG_SIT + 10)
#define ID_SPRITE_MARIO_BIG_SIT_RIGHT (ID_SPRITE_MARIO_BIG_SIT + 20)
#define ID_SPRITE_MARIO_BIG_BRACE (ID_SPRITE_MARIO_BIG + 600)
#define ID_SPRITE_MARIO_BIG_BRACE_LEFT (ID_SPRITE_MARIO_BIG_BRACE + 10)
#define ID_SPRITE_MARIO_BIG_BRACE_RIGHT (ID_SPRITE_MARIO_BIG_BRACE + 20)
#define ID_SPRITE_MARIO_BIG_HOLD (ID_SPRITE_MARIO_BIG + 700)
#define ID_SPRITE_MARIO_BIG_HOLD_LEFT (ID_SPRITE_MARIO_BIG_HOLD + 10)
#define ID_SPRITE_MARIO_BIG_HOLD_RIGHT (ID_SPRITE_MARIO_BIG_HOLD + 20)

#define ID_SPRITE_MARIO_DIE (ID_SPRITE_MARIO + 4000)

#define ID_SPRITE_MARIO_SMALL (ID_SPRITE_MARIO + 2000)
#define ID_SPRITE_MARIO_SMALL_IDLE (ID_SPRITE_MARIO_SMALL + 100)
#define ID_SPRITE_MARIO_SMALL_IDLE_LEFT (ID_SPRITE_MARIO_SMALL_IDLE + 10)
#define ID_SPRITE_MARIO_SMALL_IDLE_RIGHT (ID_SPRITE_MARIO_SMALL_IDLE + 20)

#define ID_SPRITE_MARIO_SMALL_WALKING (ID_SPRITE_MARIO_SMALL + 200)
#define ID_SPRITE_MARIO_SMALL_WALKING_LEFT (ID_SPRITE_MARIO_SMALL_WALKING + 10)
#define ID_SPRITE_MARIO_SMALL_WALKING_RIGHT (ID_SPRITE_MARIO_SMALL_WALKING + 20)
#define ID_SPRITE_MARIO_SMALL_RUNNING (ID_SPRITE_MARIO_SMALL + 300)
#define ID_SPRITE_MARIO_SMALL_RUNNING_LEFT (ID_SPRITE_MARIO_SMALL_RUNNING + 10)
#define ID_SPRITE_MARIO_SMALL_RUNNING_RIGHT (ID_SPRITE_MARIO_SMALL_RUNNING + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP (ID_SPRITE_MARIO_SMALL + 400)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK (ID_SPRITE_MARIO_SMALL_JUMP + 10)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN (ID_SPRITE_MARIO_SMALL_JUMP + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 6)

#define ID_SPRITE_MARIO_SMALL_SIT (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_SIT_LEFT (ID_SPRITE_MARIO_SMALL_SIT + 10)
#define ID_SPRITE_MARIO_SMALL_SIT_RIGHT (ID_SPRITE_MARIO_SMALL_SIT + 20)

#define ID_SPRITE_MARIO_SMALL_BRACE (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_BRACE_LEFT (ID_SPRITE_MARIO_SMALL_BRACE + 10)
#define ID_SPRITE_MARIO_SMALL_BRACE_RIGHT (ID_SPRITE_MARIO_SMALL_BRACE + 20)
#define ID_SPRITE_MARIO_SMALL_HOLD (ID_SPRITE_MARIO_SMALL + 700)
#define ID_SPRITE_MARIO_SMALL_HOLD_LEFT (ID_SPRITE_MARIO_SMALL_HOLD + 10)
#define ID_SPRITE_MARIO_SMALL_HOLD_RIGHT (ID_SPRITE_MARIO_SMALL_HOLD + 20)

#define ID_SPRITE_MARIO_MAX (ID_SPRITE_MARIO + 3000)
#define ID_SPRITE_MARIO_MAX_IDLE (ID_SPRITE_MARIO_MAX + 100)
#define ID_SPRITE_MARIO_MAX_IDLE_LEFT (ID_SPRITE_MARIO_MAX_IDLE + 10)
#define ID_SPRITE_MARIO_MAX_IDLE_RIGHT (ID_SPRITE_MARIO_MAX_IDLE + 20)

#define ID_SPRITE_MARIO_MAX_WALKING (ID_SPRITE_MARIO_MAX + 200)
#define ID_SPRITE_MARIO_MAX_WALKING_LEFT (ID_SPRITE_MARIO_MAX_WALKING + 10)
#define ID_SPRITE_MARIO_MAX_WALKING_RIGHT (ID_SPRITE_MARIO_MAX_WALKING + 20)
#define ID_SPRITE_MARIO_MAX_RUNNING (ID_SPRITE_MARIO_MAX + 300)
#define ID_SPRITE_MARIO_MAX_RUNNING_LEFT (ID_SPRITE_MARIO_MAX_RUNNING + 10)
#define ID_SPRITE_MARIO_MAX_RUNNING_RIGHT (ID_SPRITE_MARIO_MAX_RUNNING + 20)
#define ID_SPRITE_MARIO_MAX_JUMP (ID_SPRITE_MARIO_MAX + 400)
#define ID_SPRITE_MARIO_MAX_JUMP_WALK (ID_SPRITE_MARIO_MAX_JUMP + 10)
#define ID_SPRITE_MARIO_MAX_JUMP_WALK_LEFT (ID_SPRITE_MARIO_MAX_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_MAX_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_MAX_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_MAX_JUMP_RUN (ID_SPRITE_MARIO_MAX_JUMP + 20)
#define ID_SPRITE_MARIO_MAX_JUMP_RUN_LEFT (ID_SPRITE_MARIO_MAX_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_MAX_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_MAX_JUMP_RUN + 6)

#define ID_SPRITE_MARIO_MAX_SIT (ID_SPRITE_MARIO_MAX + 500)
#define ID_SPRITE_MARIO_MAX_SIT_LEFT (ID_SPRITE_MARIO_MAX_SIT + 10)
#define ID_SPRITE_MARIO_MAX_SIT_RIGHT (ID_SPRITE_MARIO_MAX_SIT + 20)

#define ID_SPRITE_MARIO_MAX_BRACE (ID_SPRITE_MARIO_MAX + 500)
#define ID_SPRITE_MARIO_MAX_BRACE_LEFT (ID_SPRITE_MARIO_MAX_BRACE + 10)
#define ID_SPRITE_MARIO_MAX_BRACE_RIGHT (ID_SPRITE_MARIO_MAX_BRACE + 20)
#define ID_SPRITE_MARIO_MAX_HOLD (ID_SPRITE_MARIO_MAX + 700)
#define ID_SPRITE_MARIO_MAX_HOLD_LEFT (ID_SPRITE_MARIO_MAX_HOLD + 10)
#define ID_SPRITE_MARIO_MAX_HOLD_RIGHT (ID_SPRITE_MARIO_MAX_HOLD + 20)


#pragma endregion 

#define ID_SPRITE_BRICK 20000

#define ID_SPRITE_GOOMBA 30000
#define ID_SPRITE_GOOMBA_WALK (ID_SPRITE_GOOMBA + 1000)
#define ID_SPRITE_GOOMBA_DIE (ID_SPRITE_GOOMBA + 2000)

#define ID_SPRITE_COIN 40000

#define ID_SPRITE_CLOUD 50000
#define ID_SPRITE_CLOUD_BEGIN (ID_SPRITE_CLOUD+1000)
#define ID_SPRITE_CLOUD_MIDDLE (ID_SPRITE_CLOUD+2000)
#define ID_SPRITE_CLOUD_END (ID_SPRITE_CLOUD+3000)

#define ID_ANI_KOOPAS_WALKING 6000
#define ID_ANI_KOOPAS_SHELL 6001
#define ID_ANI_KOOPAS_SHELL_MOVING 6002

#define ID_ANI_WINGED_GOOMBA_WALKING 8000
#define ID_ANI_WINGED_GOOMBA_DIE 8001
#define ID_ANI_WINGED_GOOMBA_FLYING 8002
#define ID_ANI_WINGED_GOOMBA_FLYING_LEFT 8003
#define ID_ANI_WINGED_GOOMBA_FALL 8004

#define ID_SPRITE_PIRANHA_PLANT 120000 // ID sprite cho Piranha Plant
#define ID_ANI_PIRANHA_PLANT_UP_DOWN 12000 // ID animation cho trạng thái lên/xuống
#define ID_SPRITE_BREAKABLE_BRICK 14001 
#define ID_ANI_BUTTON_IDLE 14300
#define ID_ANI_BUTTON_CLOSE 14300
#define ID_ANI_EXPLODE 80000 
#define ID_GREEN_MUSHROOM_SPRITE 110001
#define ID_ANI_MARIO_DIVE_IN 1006
#define MARIO_STATE_GROWING 999
#define MARIO_STATE_GROWING_LEFT 998
#define MARIO_STATE_SHRINKING 666
#define MARIO_STATE_SHRINKING_LEFT 665